BankingApplication.WebApp/Models/BalanceEnquiry.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BankingApplication.WebApp.Models
{
    public class BalanceEnquiry
    {
        public string AccountNo { get; set; }
        public string FirstName { get; set; }
        public string Balance { get; set; }
    }
}

BankingApplication.WebApp/Controllers/ManagerController.cs
using BankingApplication.BusinessLayer.Contracts;
using BankingApplication.CommonLayer.Models;
using BankingApplication.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BankingApplication.WebApp.Controllers
{
    public class ManagerController : Controller
    {
        #region Private
        private readonly ICustomerManager customerManager;
        private readonly IAccountManager accountManager;
        #endregion

        #region Public Methods
        public ManagerController(ICustomerManager customerManager,IAccountManager accountManager)
        {
            this.customerManager = customerManager;
            this.accountManager = accountManager;
        }

        [HttpGet]
        public IActionResult AddCustomer()
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult AddCustomer(CreateCustomerVM customerVM)
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {

                if (customerVM.Dob < DateTime.Now)
                {
                    var managerId = HttpContext.Session.GetString("userId");
                    var customerEmail = customerManager.GetCustomer(customerVM.EmailId, managerId, true);
                    if (customerEmail != null)
                    {
                        ViewData["AddError"] = "Email-Id already Exist,Customer Creation Failed!";
                        return View();
                    }

                    var newCustomer = new Customer()
                    {
                        FirstName = customerVM.FirstName,
                        LastName = customerVM.LastName,
                        Dob = customerVM.Dob,
                        EmailId = customerVM.EmailId,
                        MobileNumber = customerVM.MobileNumber,
                        Gender = customerVM.Gender,
                        City = customerVM.City,
                        State = customerVM.State,
                        Pincode = customerVM.Pincode,
                        ManagerId = managerId
                    };
                    string customerId = customerManager.AddCustomer(newCustomer);
                    if (customerId == null)
                    {
                        ViewData["AddError"] = "Failed to add Customer";
                    }
                    else
                    {
                        ViewData["message"] = "Successfully added customer with ID: " + customerId;
                        return View("Confirm");
                    }
                }
                else
                {
                    ViewData["AddError"] = "Invalid DOB, Customer Creation Failed!";
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult GetCustomer()
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult GetCustomer(GetCustomerVM getCustomer)
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            var managerId = HttpContext.Session.GetString("userId");
            var customer = this.customerManager.GetCustomer(getCustomer.CustomerId,managerId);
            if(customer == null)
            {
                ViewData["GetCustomer"] = "Customer with given ID not found or is unable to access";
                return View();
            }
            TempData["customerId"] = getCustomer.CustomerId;
            return RedirectToAction("EditCustomer");
        }

        [HttpGet]
        public IActionResult EditCustomer(Customer customer)
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
            
        [HttpPost]
        public IActionResult EditCustomer(UpdateCustomerVM customerVM)
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                string customerId = Convert.ToString(TempData["customerId"]);
                var updateCustomer = new BankingApplication.CommonLayer.Models.Customer()
                {
                    CustomerId = customerId,
                    FirstName = customerVM.FirstName,
                    LastName = customerVM.LastName,
                    Dob = customerVM.Dob,
                    EmailId = customerVM.EmailId,
                    MobileNumber = customerVM.MobileNumber,
                    Gender = customerVM.Gender,
                    City = customerVM.City,
                    State = customerVM.State,
                    Pincode = customerVM.Pincode
                };
                if (customerManager.UpdateCustomer(updateCustomer))
                {
                    ViewData["message"] = "Successfully updated customer with ID: " + customerId;
                    return View("Confirm");
                }
            }
            ViewData["UpdateError"] = "Unable to update Customer";
            return View();
        }

        [HttpGet]
        public IActionResult DeleteCustomer()
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult DeleteCustomer(GetCustomerVM customerVM)
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            if (this.customerManager.DeleteCustomer(customerVM.CustomerId))
            {
                ViewData["message"] = "Successfully deleted customer with ID: " + customerVM.CustomerId;
                return View("Confirm");
            }
            ViewData["DeleteCustomerError"] = "Failed to delete the account";
            return View();
        }

        [HttpGet]
        public IActionResult CreateAccount()
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult CreateAccount(AccountCreationVM accountVM)
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            string acNo = string.Empty;

            if (ModelState.IsValid)
            {
                var newAccount = new Account()
                {
                    AccountType = accountVM.AccountType,
                    Balance = accountVM.Balance,
                    CustomerId = accountVM.CustomerId,
                    Doc = DateTime.UtcNow,
                    Ifsc = accountVM.IFSC,
                    Tin = accountVM.Tin
                };

                if (accountVM.AccountType.Equals("saving"))
                {
                    var oldAccount = accountManager.GetAccount(newAccount);

                    if (oldAccount == null)
                    {
                        acNo = AddNewAccount(newAccount);
                    }
                }

                else if (accountVM.AccountType.Equals("current"))
                {
                    var oldAccount = accountManager.GetCustomerAccounts(accountVM.CustomerId);
                    foreach(var acc in oldAccount)
                    {
                        if (acc.Tin.Equals(accountVM.Tin))
                        {
                            ViewData["CreateAccount"] = "TIN already registered";
                            return View();
                        }
                    }
                    acNo = AddNewAccount(newAccount);
                }

                else if (accountVM.AccountType.Equals("corporate"))
                {
                    var oldAccount = accountManager.GetAccount(newAccount);
                    if(oldAccount == null)
                    {
                        acNo = AddNewAccount(newAccount);
                    }
                }
            }

            if (String.IsNullOrEmpty(acNo))
            {
                ViewData["CreateAccount"] = "Failed to create the account";
                return View();
            }

            ViewData["message"] = "Account created with" + acNo;
            return View("Confirm");
        }

        [HttpGet]
        public IActionResult GetAccount()
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        [HttpPost]
        public IActionResult GetAccount(GetAccountVM getAccount)
        {
            if (SessionValid())
            {
                return RedirectToAction("Login", "Account");
            }

            var account = this.accountManager.GetAccount(getAccount.AccountId);

            if (account == null)
            {
                //ViewData["message"] = "Failed to find the account";
                ModelState.AddModelError("Password", "Invalid login attempt.");
                return View();
            }


BankingApplication.WebApp/Views/Manager/AddCustomer.cshtml
@model BankingApplication.WebApp.Models.CreateCustomerVM

@{
    ViewData["Title"] = "AddCustomer";
}


<h4>Customer Creation</h4>
@if (ViewData.ContainsKey("AddError"))
{
    <div class="alert alert-info">

        <strong>@ViewData["AddError"]</strong>

    </div>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddCustomer" asp-controller="Manager" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select id="Gender" name="Gender">
                    <option selected>Select</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dob" class="control-label"></label>
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailId" class="control-label"></label>
                <input asp-for="EmailId" class="form-control" />
                <span asp-validation-for="EmailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pincode" class="control-label"></label>
                <input asp-for="Pincode" class="form-control" />
                <span asp-validation-for="Pincode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BankingApplication.WebApp/Views/Manager/BackupDeleteAccount.cshtml
@model BankingApplication.WebApp.Models.DeleteAccountVM

@{
    ViewData["Title"] = "DeleteAccount";
}

<h1>DeleteAccount</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteAccount">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <input asp-for="AccountId" class="form-control" />
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


BankingApplication.WebApp/Views/Manager/BalanceEnquiry.cshtml

@{
    ViewData["Title"] = "BalanceEnquiry";
}

<h1>BalanceEnquiry</h1>
<hr />
<div class="row">
    <div class="jumbotron">
        <div class="col-md-6">
            <form>
                <div class="form-group row">
                    <label class="custom-control-label">AccountNo</label>
                    <div class="col-sm-10">
                        <input type="text" readonly class="form-control-plaintext" id="AccountNo" value=@ViewBag.AccountNo>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Balance</label>
                    <div class="col-sm-10">
                        <input type="text" readonly class="form-control-plaintext" id="AccountNo" value=@ViewBag.Balance>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

BankingApplication.WebApp/Views/Manager/CreateAccount.cshtml
@model BankingApplication.WebApp.Models.AccountCreationVM

@{
    ViewData["Title"] = "CreateAccount";
}

<h1>CreateAccount</h1>
<hr />
@if (ViewData.ContainsKey("CreateAccount"))
{
    <div class="alert alert-info">

        <strong>@ViewData["CreateAccount"]</strong>

    </div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateAccount" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Balance" class="control-label"></label>
                <input asp-for="Balance" class="form-control" />
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tin" class="control-label"></label>
                <input asp-for="Tin" class="form-control" />
                <span asp-validation-for="Tin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountType" class="control-label"></label>
                <select id="AccountType" name="AccountType">
                    <option selected>Select</option>
                    <option value="saving">Saving</option>
                    <option value="current">Current</option>
                    <option value="corporate">Corporate</option>
                </select>
                <span asp-validation-for="AccountType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IFSC" class="control-label"></label>
                <input asp-for="IFSC" class="form-control" />
                <span asp-validation-for="IFSC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


BankingApplication.WebApp/Views/Manager/DeleteAccount.cshtml
@model BankingApplication.WebApp.Models.DeleteAccountVM

@{
    ViewData["Title"] = "DeleteAccount";
}

<h1>DeleteAccount</h1>
@if (ViewData.ContainsKey("DeleteACError"))
{
    <div class="alert alert-info">

        <strong>@ViewData["DeleteACError"]</strong>

    </div>
}
<hr />
<p>AccountNo:@ViewBag.AccountNo</p>
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteAccount">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IsDelete" class="control-label"></label>
                <select id="IsDelete" name="IsDelete">
                    <option selected>Select Confirmation</option>
                    <option value="Yes">Yes</option>
                    <option value="No">No</option>
                </select>
                <span asp-validation-for="IsDelete" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Confirm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


BankingApplication.WebApp/Views/Manager/DeleteCurrentAccount.cshtml
@model BankingApplication.WebApp.Models.DeleteCurrentVM

@{
    ViewData["Title"] = "DeleteCurrentAccount";
}

<h1>DeleteCurrentAccount</h1>

<h4>DeleteCurrentVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteCurrentAccount">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TIN" class="control-label"></label>
                <input asp-for="TIN" class="form-control" />
                <span asp-validation-for="TIN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


BankingApplication.WebApp/Views/Manager/DeleteCustomer.cshtml
@model BankingApplication.WebApp.Models.GetCustomerVM

@{
    ViewData["Title"] = "DeleteCustomer";
}

<h1>DeleteCustomer</h1>
@if (ViewData.ContainsKey("DeleteCustomerError"))
{
    <div class="alert alert-info">

        <strong>@ViewData["DeleteCustomerError"]</strong>

    </div>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="DeleteCustomer" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


BankingApplication.WebApp/Views/Manager/EditCustomer.cshtml
@model BankingApplication.WebApp.Models.UpdateCustomerVM

@{
    ViewData["Title"] = "EditCustomer";
}

<h1>EditCustomer</h1>
@if (ViewData.ContainsKey("UpdateError"))
{
    <div class="alert alert-info">

        <strong>@ViewData["UpdateError"]</strong>

    </div>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditCustomer" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select id="Gender" name="Gender">
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dob" class="control-label"></label>
                <input asp-for="Dob" class="form-control" />
                <span asp-validation-for="Dob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailId" class="control-label"></label>
                <input asp-for="EmailId" class="form-control" />
                <span asp-validation-for="EmailId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pincode" class="control-label"></label>
                <input asp-for="Pincode" class="form-control" />
                <span asp-validation-for="Pincode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


BankingApplication.WebApp/Views/Manager/GetAccount.cshtml
@model BankingApplication.WebApp.Models.GetAccountVM

@{
    ViewData["Title"] = "GetAccount";
}

<h1>GetAccount</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="GetAccount">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccountId" class="control-label"></label>
                <input asp-for="AccountId" class="form-control" />
                <span asp-validation-for="AccountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


BankingApplication.WebApp/Views/Manager/GetCustomer.cshtml
@model BankingApplication.WebApp.Models.GetCustomerVM

@{
    ViewData["Title"] = "GetCustomer";
}

<h1>GetCustomer</h1>
@if (ViewData.ContainsKey("GetCustomer"))
{
    <div class="alert alert-info">

        <strong>@ViewData["GetCustomer"]</strong>

    </div>
}
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="GetCustomer" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


BankingApplication.WebApp/Views/Manager/UpdateAccount.cshtml
@model BankingApplication.WebApp.Models.UpdateAccountVM

@{
    ViewData["Title"] = "UpdateAccount";
}

<h1>UpdateAccount</h1>
@if (ViewData.ContainsKey("UpdateError"))
{
    <div class="alert alert-info">

        <strong>@ViewData["UpdateError"]</strong>

    </div>
}
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateAccount" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Balance" class="control-label"></label>
                <input asp-for="Balance" class="form-control" />
                <span asp-validation-for="Balance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOC" class="control-label"></label>
                <input asp-for="DOC" class="form-control" />
                <span asp-validation-for="DOC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tin" class="control-label"></label>
                <input asp-for="Tin" class="form-control" />
                <span asp-validation-for="Tin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountType" class="control-label"></label>
                <select id="AccountType" name="AccountType">
                    <option selected>Select</option>
                    <option value="saving">Saving</option>
                    <option value="current">Current</option>
                    <option value="corporate">Corporate</option>
                </select>
                <span asp-validation-for="AccountType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IFSC" class="control-label"></label>
                <input asp-for="IFSC" class="form-control" />
                <span asp-validation-for="IFSC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
